environment:
  matrix:
    - PYTHON: "C:\\Python33-x64"
    - PYTHON: "C:\\Python34-x64"
    - PYTHON: "C:\\Python35-x64"
    - PYTHON: "C:\\Python36-x64"

build_script:
- set PATH=%PYTHON%;%PYTHON%\Scripts;%PATH%
- pip install .
- pip install nose
- nosetests
