environment:
  matrix:
    - PYTHON: "C:\\Python33-x64"
    - PYTHON: "C:\\Python34-x64"
    - PYTHON: "C:\\Python35-x64"
    - PYTHON: "C:\\Python36-x64"

build_script:
- set PATH=%PYTHON%;%PYTHON%\Scripts;%PATH%
- pip install nodepy-runtime
- nodepy https://nodepy.org/install-pm.py develop
- nodepy-pm install
- set PATH=%PATH%;.nodepy\bin
# TODO: Globbing doesn't work for some reason...
- nodepy-nosetests tests\test_build.py tests\test_core.py tests\test_dsl.py
- craftr --version
