language: python
python:
- '3.6.0'
- '3.6.1'
- '3.6.2'
- nightly

matrix:
- fast_finish: true

env:
- BUILD_MODULE=examples/java BUILD_OPTIONS=":main_run -d java.dist_type=onejar"
- BUILD_MODULE=examples/java BUILD_OPTIONS=":main_run -d java.dist_type=merge"
- BUILD_MODULE=examples/csharp BUILD_OPTIONS=":main_run"

before_install:
- if [[ "$BUILD_MODULE" == "examples/csharp" ]]; then
    sudo apt-get -qq -y update > /dev/null;
    sudo apt-get -qq -y install mono-complete gtk-sharp2 > /dev/null;
  fi

install:
- sudo apt-get update
- pip install git+https://github.com/nodepy/nodepy.git@develop
- nodepy --version
- nodepy https://nodepy.org/install-pm master
- nodepy-pm install -I
- export PATH="$(nodepy-pm bin):$PATH"

script:
- nodepy-pm run test
- craftr -p${BUILD_MODULE} $BUILD_OPTIONS -bbuild -v
