language: python
python:
- 3.3
- 3.4
- 3.5
- 3.6
install:
- pip install nodepy-runtime
- nodepy https://nodepy.org/install-pm.py develop
- nodepy-pm install
- export PATH="$PATH:$(nodepy-pm bin)"
script:
- nodepy-nosetests tests/*
- craftr --version
