language: python
python:
- 3.6
- nightly

# XXX Ideally we only want these to be installed when necessary.
addons:
  apt:
    sources:
      - sourceline: deb http://download.mono-project.com/repo/debian trusty/snapshots/5.2.0.224 main
        key_url: http://keyserver.ubuntu.com/pks/lookup?op=get&search=0xA6A19B38D3D831EF
      - sourceline: deb [arch=amd64] https://packages.microsoft.com/repos/microsoft-ubuntu-trusty-prod trusty main
        key_url: https://packages.microsoft.com/keys/microsoft.asc
      - packages:
    packages:
      - mono-devel
      - ca-certificates-mono

env:
- BUILD_MODULE=examples/java BUILD_OPTIONS=":main_run --options java.dist_type=onejar"
- BUILD_MODULE=examples/java BUILD_OPTIONS=":main_run --options java.dist_type=merge"
- BUILD_MODULE=examples/csharp BUILD_OPTIONS=":main_run"

install:
- sudo apt-get update
- pip install git+https://github.com/nodepy/nodepy.git@develop
- nodepy --version
- nodepy https://nodepy.org/install-pm master
- nodepy-pm install -I
- export PATH="$(nodepy-pm bin):$PATH"

script:
- nodepy-pm run test
- craftr --configure ${BUILD_MODULE} --build $BUILD_OPTIONS
