[package]
name = "craftr"
version = "3.0.0"
description = "The Craftr build system core application."
license = "MIT"
main = "./lib/api"
resolve_root = "lib"

[authors]
"Niklas Rosenstein" = { email = "rosensteinniklas@gmail.com" }

[dependencies.python]
sumtypes = ">=0.1a4"
glob2 = ">=0.6"
