name: craftr
version: 4.0.0
author: Niklas Rosenstein <rosensteinniklas@gmail.com>
description: A Python based meta build system for various languages.
license: MIT
url: https://github.com/craftr-build/craftr
requirements:
- python ^3.6
- databind.core ^0.9.0
- glob2 ~0.6
- nodepy-runtime ~2.1.5
- nr.collections ^0.1.1
- nr.interface ~0.0.1
- nr.fs ^1.1.1
- nr.stream ~0.0.1
- nr.sumtype ~0.0.1
- requests ^2.19.1
- termcolor ^1.1.0
- toml ^0.9.4
- werkzeug ^0.14.1
entrypoints:
  console_scripts:
  - craftr = craftr.main:main
