
environment:
  matrix:
  - BUILD_MODULE: examples/java
    BUILD_OPTIONS: :main_run --options java.dist_type=onejar
    ADD_PATH: C:\Program Files\Java\jdk1.8.0\bin
    ALLOW_FAILURE: true  # JVM runs out of RAM when using onejar + tensorflow

  - BUILD_MODULE: examples/java
    BUILD_OPTIONS: :main_run --options java.dist_type=merge

  - BUILD_MODULE: examples/csharp
    APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017

  - BUILD_MODULE: examples/csharp
    APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015

  ###
  # NuGet Version is too low in this image to run the C# example.
  # Newtonsoft.Json requires NuGet 2.12 but 2.8 is installed.
  ###
  #- BUILD_MODULE: examples/csharp
  #  APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2013

  - BUILD_MODULE: examples/csharp
    BUILD_OPTIONS: :main_run --options csharp.impl=mono csharp.csc=mcs
    APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015  # 2013 and 2015 have support for Mono
    ADD_PATH: C:\Program Files (x86)\Mono\bin

  - BUILD_MODULE: examples/csharp
    BUILD_OPTIONS: :main_run --options csharp.impl=mono csharp.csc=mcs
    APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015

  - BUILD_MODULE: examples/cxx
    BUILD_OPTIONS: :main_run="--hex 42"

  - BUILD_MODULE: examples/cxx-shared
    BUILD_OPTIONS: :main_run

  - BUILD_MODULE: examples/cxx
    BUILD_OPTIONS: :main_run --options cxx.compiler=mingw

  - BUILD_MODULE: examples/cxx-shared
    BUILD_OPTIONS: :main_run --options cxx.compiler=mingw

matrix:
  allow_failures:
    - ALLOW_FAILURE: true

build_script:
- set PATH=C:\Python36-x64;C:\Python36-x64\Scripts;%PATH%;%ADD_PATH%
- pip --version
- pip install wheel
- pip install git+https://github.com/nodepy/nodepy.git@develop
- nodepy --version
- nodepy https://nodepy.org/install-pm develop
- nodepy-pm install -PI
- set PATH=.nodepy/bin;%PATH%
- craftr --configure %BUILD_MODULE% --build %BUILD_OPTIONS%
